server:
  port: 8081

spring:
  application:
    name: iBeer
  main:
    allow-bean-definition-overriding: true
  messages:
    encoding: 'UTF-8'
    basename: config.i18n.messages
  banner:
    charset: 'UTF-8'
    location: classpath:static/banner.txt

  datasource:
    url: jdbc:mariadb://localhost:3306/ibeer_db?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: org.mariadb.jdbc.Driver
    username: ${MYSQL_USER:ibeer}
    password: ${MYSQL_PASSWORD:Bk55yc1u0eiqga6e}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.json

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

  metrics:
    tags:
      application: ibeer-service
    enable:
      jvm: true
    distribution:
      percentiles[http.server.requests]: 0.5, 0.90, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      slo[http.server.requests]: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s

      percentiles[http.client.requests]: 0.5, 0.90, 0.95, 0.99
      percentiles-histogram[http.client.requests]: true
      slo[http.client.requests]: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s

api-info:
  swagger-ui:
    title: "REST support for iBeer API"
    description: "This is the REST UI support of iBeer API. Here you can perform REST operations on the API."
    license: "Apache License 2.0"
    version: "1.0.0"
    base_package: "com.ipaixao.ibeer"
    contact_name: "Iago Paixao"
    contact_url: "https://github.com/iagopaixao/ibeer-service"
    contact_email: "euiagopaixao@gmail.com"