server:
  port: 8081

spring:
  application:
    name: iBeer
  main:
    allow-bean-definition-overriding: true
  banner:
    charset: 'UTF-8'
    location: classpath:static/banner.txt
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    producer:
      topic: beer-created
      client-id: beer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://localhost:5432/ibeer_db
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.json

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

  metrics:
    tags:
      application: ibeer-service
    enable:
      jvm: true
    distribution:
      percentiles-histogram[http.server.requests]: true
      percentiles[http.server.requests]: 0.5, 0.90, 0.95, 0.99
      slo[http.server.requests]: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s

      percentiles-histogram[http.client.requests]: true
      percentiles[http.client.requests]: 0.5, 0.90, 0.95, 0.99
      slo[http.client.requests]: 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s

api-info:
  swagger-ui:
    title: "REST support for iBeer API"
    description: "This is the REST UI support of iBeer API. Here you can perform REST operations on the API."
    license: "Apache License 2.0"
    version: "1.0.0"
    base_package: "com.ipaixao.ibeer"
    contact_name: "Iago Paixao"
    contact_url: "https://github.com/iagopaixao/ibeer-service"
    contact_email: "euiagopaixao@gmail.com"