version: '3.9'

networks:
  ibeer_app_network:
    driver: bridge
  ibeer_obervability_network:
    driver: bridge

services:
  redis-ibeer:
    image: redis
    container_name: redis_ibeer
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - ibeer_app_network

  postgres-ibeer:
    container_name: ibeer_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - ibeer_app_network
    environment:
      POSTGRES_DB: ibeer_db
      POSTGRES_PASSWORD: secret

#  ibeer-service:
#    platform: linux/x86_64
#    container_name: ibeer_service
#    build:
#      context: ../
#      dockerfile: Dockerfile
#    image: ibeer-service
#    ports:
#      - '8081:8081'
#    depends_on:
#      - postgres-ibeer
#      - redis-ibeer
#    networks:
#      - ibeer_app_network
#    env_file:
#      - ./env-vars.env
#    environment:
#      SPRING_DATASOURCE_URL: $POSTGRES_DATABASE_URL
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD-SHELL" "curl -f http://localhost:8081/health || exit 1"]
#      interval: 45s
#      timeout: 10s
#      retries: 3

  prometheus-ibeer:
    image: prom/prometheus:latest
    container_name: prometheus_ibeer
    restart: unless-stopped
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      #      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - ibeer_obervability_network
      - ibeer_app_network

  alertmanager-ibeer:
    image: prom/alertmanager
    container_name: alertmanager_ibeer
    volumes:
      - ./observability/alertmanager:/etc/alertmanager/:ro
    ports:
      - '9093:9093'
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - ibeer_obervability_network
    depends_on:
      - prometheus-ibeer

  grafana-ibeer:
    image: grafana/grafana
    container_name: grafana_ibeer
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - ibeer_obervability_network
    depends_on:
      - prometheus-ibeer
      - alertmanager-ibeer