version: '3.9'

networks:
#  ibeer_cache_network:
#    internal: true
  ibeer_db_network:
    internal: true
#  ibeer_api_network:
#    internal: true
#  proxy_ibeer_nework:

volumes:
  ibeer_db_data:
    driver: local

services:
#  redis_ibeer:
#    image: redis
#    container_name: ibeer_cache
#    restart: unless-stopped
#    expose:
#      - 6379
#    networks:
#      - ibeer_cache_network

  mysql_ibeer:
    image: mysql
    container_name: mysql_ibeer
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'ibeer_db'
      MYSQL_USER: 'ibeer'
      MYSQL_PASSWORD: 'Bk55yc1u0eiqga6e'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/ibeer_db_data
    ports:
      - '3306:3306'
#    networks:
#      - ibeer_db_network

#  ibeer-app:
#    platform: linux/x86_64
#    container_name: ibeer_app
#    command:
#      - './gradlew -S -i --parallel clean bootJar'
#    build:
#      context: ../
#      dockerfile: Dockerfile
#    image: ibeer-app
#    depends_on:
#      - postgres_ibeer
#      - redis_ibeer
#    networks:
#      - ibeer_api_network
#      - ibeer_db_network
#      - ibeer_cache_network
#    restart: unless-stopped
#    healthcheck:
#      test: 'curl -sS http://localhost/health'
#      interval: 1s
#      timeout: 30s
#      retries: 60
#
#  proxy-ibeer:
#    image: nginx
#    container_name: proxy_ibeer
#    restart: unless-stopped
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
#    ports:
#      - '80:80'
#    networks:
#      - proxy_ibeer_nework
#      - ibeer_api_network
#    depends_on:
#      - ibeer-app