version: '3.9'

networks:
  ibeer_obervability_network:
    driver: bridge

services:
  prometheus-ibeer:
    image: prom/prometheus:latest
    container_name: prometheus_ibeer
    restart: unless-stopped
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      #      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - ibeer_obervability_network

  alertmanager-ibeer:
    image: prom/alertmanager
    container_name: alertmanager_ibeer
    volumes:
      - ./observability/alertmanager:/etc/alertmanager/:ro
    ports:
      - '9093:9093'
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - ibeer_obervability_network
    depends_on:
      - prometheus-ibeer

  grafana-ibeer:
    image: grafana/grafana
    container_name: grafana_ibeer
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - ibeer_obervability_network
    depends_on:
      - prometheus-ibeer
      - alertmanager-ibeer