global:
  scrape_interval: 5s

#rule_files:
#  - alert.rules
#
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#            - alertmanager-forum-api:9093

scrape_configs:
  - job_name: prometheus-ibeer-service
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: ibeer-service
    metrics_path: '/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8081