{
 "title": "dash-observability-ibeer-app",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "Hora de inicialização da API",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "Tempo de atividade da API",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USER AUTH ERRORS",
   "type": "stat",
   "description": "Erros de autenticação de usuários no último minuto ",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_error_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONNECTION STATE",
   "type": "timeseries",
   "description": "Estado das conexões com o banco de dados",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "DB CONNECTION TIMEOUT",
   "type": "stat",
   "description": "Número de conexões que ocorreram timeout com o banco dados",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "Pool de conexões JDBC",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USERS LOGGED",
   "type": "stat",
   "description": "Usuários logados no último minuto",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONNECTION CREATION TIME",
   "type": "timeseries",
   "description": "Tempo de criação de uma conexão do banco de dados",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "  hikaricp_connections_creation_seconds_sum{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}\n/\n  hikaricp_connections_creation_seconds_count{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "CONNECTION ACQUIRE TIME",
   "type": "timeseries",
   "description": "Tempo de aquisição de conexões do banco de dados",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  hikaricp_connections_acquire_seconds_sum{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}\n/\n  hikaricp_connections_acquire_seconds_count{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  {
   "title": "CONNECTION USAGE TIME",
   "type": "timeseries",
   "description": "Tempo de uso de uma conexão do banco de dados",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  hikaricp_connections_usage_seconds_sum{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}\n/\n  hikaricp_connections_usage_seconds_count{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "description": "Eventos de nível  WARN e ERROR que chegaram aos logs nos últimos 5 minutos",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", level=\"warn\"}[5m]))",
     "legendFormat": "warn"
    },
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m])",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "NON-HEAP USED",
   "type": "gauge",
   "description": "Percentual de utilização da memória NON-HEAP",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", area=\"nonheap\"}) \n* 100 / \nsum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU UTILIZATION",
   "type": "timeseries",
   "description": "Consumo de CPU pelo sistema e processo ",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\"} * 100",
     "legendFormat": "System CPU usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 100",
     "legendFormat": "Process CPU usage"
    }
   ]
  },
  {
   "title": "HEAP USED",
   "type": "gauge",
   "description": "Percentual de utilização da memória HEAP",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", area=\"heap\"}) \n* 100 / \nsum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU LOAD AVERAGE",
   "type": "timeseries",
   "description": "Média de consumo de CPU",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\"} * 100",
     "legendFormat": "Load average [1m]"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "CPU core size"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "TOTAL REQUESTS - LAST MIN",
   "type": "stat",
   "description": "Quantidade de requisições no último minuto",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Quantidade de erros 500 no último minuto",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "description": "Latência média por minuto",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(\n      http_server_requests_seconds_bucket{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!=\"/actuator/prometheus\"}[1m]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    rate(\n      http_server_requests_seconds_bucket{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!=\"/actuator/prometheus\"}[1m]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le) (\n    rate(\n      http_server_requests_seconds_bucket{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!=\"/actuator/prometheus\"}[1m]\n    )\n  )\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(\n      http_server_requests_seconds_bucket{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!=\"/actuator/prometheus\"}[1m]\n    )\n  )\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(\n  0.25,\n  sum by (le) (\n    rate(\n      http_server_requests_seconds_bucket{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!=\"/actuator/prometheus\"}[1m]\n    )\n  )\n)",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Taxa de erros nos últimos 5 minutos",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum(\n    rate(\n      http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",status=~\".*5.*|.*4.*\",uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}[5m]\n    )\n  ) by (uri)\n/\n  sum(\n    rate(\n      http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}[5m]\n    )\n  ) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Tempo de resposta no último minuto",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(\n    http_server_requests_seconds_sum{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\", uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}[1m]\n  )\n/\n  rate(\n    http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}[1m]\n  )",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "Quantidade de requisições por endpoint no último minuto",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (uri) (\n  increase(\n    http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}[1m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "description": "Tempo médio de duração das requisições no último minuto",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(\n    http_server_requests_seconds_sum{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",status=~\".*2.*\",uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}[1m]\n  )\n/\n  rate(\n    http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",job=\"ibeer-api\",status=~\".*2.*\",uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}[1m]\n  )",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "MAX REQUESTS DURATION",
   "type": "timeseries",
   "description": "Tempo máximo de duração das requisições",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"ibeer-api\", status=~\".*2.*\", uri!~\".*api-docs.*|.*swagger.*|.*actuator.*|.*UNK.*\"}",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  }
 ]
}