name: Build and Test Checker

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: x64
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build and Test
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: -S -i build
